classifications = {
	'FV':'Ship of a fishing fleet',
	'GV':  'Official service ship',
	'MM':  'Merchant ship',
	'NF':  'River vessel',
	'NS':   'Naval ship',
	'SV':  'Rescue vessel',
	'XX':   'Unspecified',
	'ACV':  'Air-cushion vessel',
	'AUX':  'Auxiliary ship',
	'AVI':  'Despatch vessel',
	'BAR':  'Lighter',
	'BLK':  'Bulk carrier',
	'BLN':  'Whaler',
	'BLS':  'Buoy ship',
	'BTA':  'Factory ship',
	'CA':   'Cargo ship',
	'CAB':  'Coaster',
	'CBL':  'Cable ship',
	'CGT':  'Coast Guard',
	'CHA':  'Barge',
	'CHR':  'Trawler',
	'CIM':  'Cement carrier',
	'CIT':  'Tanker',
	'COA':  'Collier',
	'CON':  'Container ship',
	'COR':  'Corvette',
	'CRO':  'Cruiser',
	'CTR':  'Cutter',
	'DES':  'Destroyer',
	'DIV':  'Diving vessel',
	'DMN':  'Minesweeper',
	'DOU':  'Customs launch',
	'DRG':  'Dredger',
	'DRY':  'Dry cargo ship',
	'DUN':  'Ketch',
	'ECO':  'Training ship',
	'ESC':  'Escort ship',
	'EXP':  'Survey / research ship',
	'FBT':  'Ferry',
	'FPS':  'Fast patrol ship',
	'FRG':  'Reefer',
	'FRM':  'Weather ship',
	'FRT':  'Frigate',
	'FRU': 'Fruit carrier',
	'GEN':  'General cargo ship',
	'GOL':  'Schooner',
	'GRC':  'Grain carrier',
	'GRF':  'Floating crane',
	'GS':   'Warship',
	'HOP':  'Hospital ship',
	'HYD':  'Hydrographic ship',
	'ICE':  'Ice breaker',
	'ICN':  'Waste incinerator',
	'INS':  'Inspection ship',
	'IV':   'Trainingship (*)',
	'LAN':  'Lobster ship',
	'LOU':  'Lugger',
	'MB':   'Dry cargo ship (*)',
	'MK':   'Floating crane (*)',
	'MOR': 'Banker',
	'MOU':  'Mine layer',
	'MR':   'Vehicle carrier (*)',
	'MT':   'Tanker (*)',
	'MTB':  'Motor boat',
	'MV':  'Cargo ship (*)',
	'NET':  'Pollution and surface clearance vessel',
	'NVP': 'Naviplane',
	'OBO':  'Ore-bulk-oil carrier',
	'OIL':  'Oil tanker',
	'OSC':  'Oceanographic ship',
	'OSV': 'Ocean-station vessel',
	'PA':   'Passenger ship',
	'PAQ':  'Liner',
	'PBE':  'Livestock carrier',
	'PCH':  'Barge carrier',
	'PER':  'Drilling unit',
	'PH':   'Fishing vessel',
	'PHA':  'Lightship',
	'PHR':  'Lighthouse tender',
	'PLE':  'Platform',
	'PLT':  'Pilot',
	'PMP':  'Firefloat',
	'PMX':  'Cargo & passenger ship',
	'PON':  'Pontoon',
	'PTA':  'Aircraft carrier',
	'PTH':  'Helicopter carrier',
	'PUS':  'Pusher (*)',
	'RAM':  'Salvage ship',
	'RAV':  'Supply vessel',
	'ROC':  'Rock breaker',
	'ROU':  'Ro-Ro ship',
	'SAU':  'Rescue vessel',
	'SEC':  'Stand-by safety vessel',
	'SLO':  'Sloop',
	'SMN':  'Submarine',
	'SRV':  'Patrol ship',
	'THO':  'Tunny ship',
	'TPG':  'Liquefied gas carrier',
	'TPO':  'Ore carrier',
	'TPS':  'Solvent carrier',
	'TPT':  'Transport',
	'TPW':  'Forest-product carrier',
	'TRA':  'Tramp',
	'TUG':  'Tug / Pusher',
	'TVH':  'Vehicle carrier',
	'VDO':  'Launch',
	'VDT':  'Hydrofoil',
	'VLR':  'Sailing ship',
	'XXX':  'Unspecified',
	'YAT':  'Yacht'
}